/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(dedispersion.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(a3198c10dad4ca3b239ab167a2fd9e7d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/radio_astro/dedispersion.h>
// pydoc.h is automatically generated in the build directory
#include <dedispersion_pydoc.h>

void bind_dedispersion(py::module& m)
{

    using dedispersion    = gr::radio_astro::dedispersion;


    py::class_<dedispersion, gr::block, gr::basic_block,
        std::shared_ptr<dedispersion>>(m, "dedispersion", D(dedispersion))

        .def(py::init(&dedispersion::make),
           D(dedispersion,make)
        )
        



        ;




}








