/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(vmedian.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(0240881ebd1e4df0b7e03283572029ef)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/radio_astro/vmedian.h>
// pydoc.h is automatically generated in the build directory
#include <vmedian_pydoc.h>

void bind_vmedian(py::module& m)
{

    using vmedian    = gr::radio_astro::vmedian;

    py::class_<vmedian, gr::block, gr::basic_block,
        std::shared_ptr<vmedian>>(m, "vmedian", D(vmedian))

        .def(py::init(&vmedian::make),
           D(vmedian,make)
        )

        .def("set_vlen",
             &vmedian::set_vlen,
             py::arg("vec_length"),
             D(vmedian, set_vlen))

        .def("set_mode",
             &vmedian::set_mode,
             py::arg("n"),
             D(vmedian, set_mode))

        ;
}
