/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(vselect.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(2076042885126d4f2e5964d568cf83e6)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/radio_astro/vselect.h>
// pydoc.h is automatically generated in the build directory
#include <vselect_pydoc.h>

void bind_vselect(py::module& m)
{

    using vselect    = gr::radio_astro::vselect;


    py::class_<vselect,
	       gr::block,
	       gr::basic_block,
        std::shared_ptr<vselect>>(m, "vselect", D(vselect))

        .def(py::init(&vselect::make),
           py::arg("vec_length"),
           py::arg("vec_begin"),
           py::arg("vec_out_len"),
           D(vselect,make)
        )
        



        ;




}








