#!/bin/bash
# Script to plot Tsys Calibrated  Science Aficionado spectra
# Glen Langston, National Science Foundation
# HISTORY
# 18MAY01 Version that searches for executable t.py

# find the plotting program
if [ -e t.py ]
then
    python t.py "$@"
else
    if [ -e ~/bin/t.py ]
    then
       python ~/bin/t.py "$@"
    else  
       if [ -e ../t.py ]
       then
       	  python ../t.py "$@"
       else  
           print "Can not file Raw plotting python program: t.py" 
       fi
    fi
fi  # end else not in current directory
