/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(vsum.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(0240881ebd1e4df0b7e03283572029ef)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/radio_astro/vsum.h>
// pydoc.h is automatically generated in the build directory
#include <vsum_pydoc.h>

void bind_vsum(py::module& m)
{

    using vsum    = gr::radio_astro::vsum;

    py::class_<vsum, gr::block, gr::basic_block,
        std::shared_ptr<vsum>>(m, "vsum", D(vsum))

        .def(py::init(&vsum::make),
           D(vsum,make)
        )

        .def("set_vlen",
             &vsum::set_vlen,
             py::arg("vec_length"),
             D(vsum, set_vlen))

        .def("set_c_begin",
             &vsum::set_c_begin,
             py::arg("c_begin"),
             D(vsum, set_c_begin))

        .def("set_c_end",
             &vsum::set_c_end,
             py::arg("c_end"),
             D(vsum, set_c_end))

        ;
}
